# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleChatClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parse'
  # Pods for SampleChatClient

  target 'SampleChatClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleChatClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
